#!/bin/bash
# Check to see if running as root
echo -e "\nChecking for root."
if [ `id -u` != 0 ]; then
	echo ""
    echo "Not root."
	echo ""
    echo -e "Need to be run as root.\n"
	echo ""
    echo "Try 'sudo -s' then the script."
    echo ""
    exit 1
else
	echo ""
    echo "Root."
	echo ""
fi
# Raspberry PI configuration file
cat <<EOF >> /boot/config.txt
# Resolution 1366x768 looks good on a Full HD TV
hdmi_group=2
hdmi_mode=81
#Option hdmi_drive for DVI it's 1, for HDMI with sound (TV, adapter) it's 2
hdmi_drive=2
# Force sound out through HDMI
hdmi_force_edid_audio=1
# Don't stop HDMI if TV is closed at boot
hdmi_force_hotplug=1
# More memory for GPU means better movie decoding in Omxplayer and Kodi
gpu_mem=256
# Make sure color depth is not selected by default as 16 or 8
framebuffer_depth=24
# For camera and webm decoding to work well, load stronger boot payloads
start_file=start_x.elf
fixup_file=fixup_x.dat
# When there are bad usb cables for 5V, don't care about it
# -no warning of low voltage
avoid_warnings=1
# -no CPU turbo stopping
avoid_warnings=2
# Provide maximum 5V current to USB devices, good for external harddisk
max_usb_current=1
EOF
# Kernel - save data to disk after getting 6 seconds old with 8MB buffer
cat <<EOF > /etc/sysctl.d/30-rpi-optimizations.conf
vm.swappiness = 60
vm.min_free_kbytes = 8192
vm.vfs_cache_pressure = 500
vm.dirty_bytes = 8388608
vm.dirty_background_bytes = 8388608
vm.dirty_writeback_centisecs = 600
vm.dirty_expire_centisecs = 600
EOF
# Kernel - don't care about IPV6 at all, use only IPV4
cat <<EOF > /etc/sysctl.d/99-rpi-disable-ipv6.conf
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
EOF
# Load all sysctl configuration files manually
sysctl --system
# Show the sysctl configurations to see if they look well
sysctl -a | grep disable | grep ipv6
# Get fresh repository status and upgrade installed packages
apt-get update && apt-get upgrade -y
# Save all buffers to disk
sync
