#!/bin/bash
# Check to see if running as root
echo -e "\nChecking for root."
if [ `id -u` != 0 ]; then
	echo ""
    echo "Not root."
	echo ""
    echo -e "Need to be run as root.\n"
	echo ""
    echo "Try 'sudo -s' then the script."
    echo ""
    exit 1
else
	echo ""
    echo "Root."
	echo ""
fi
# Raspberry PI configuration file
if [ -f /boot/config.before ]
then
	rm /boot/config.txt
else
        mv /boot/config.txt /boot/config.before
fi
cat <<EOF > /boot/config.txt
# Resolution 1366x768 looks good on a Full HD TV
hdmi_group=2
hdmi_mode=81
#Option hdmi_drive for DVI it's 1, for HDMI with sound (TV, adapter) it's 2
hdmi_drive=2
# Force sound out through HDMI
hdmi_force_edid_audio=1
# Don't stop HDMI if TV is closed at boot
hdmi_force_hotplug=1
# More memory for GPU means better movie decoding in Omxplayer and Kodi
gpu_mem=256
# Make sure color depth is not selected by default as 16 or 8
framebuffer_depth=24
# For camera and webm decoding to work well, load stronger boot payloads
start_file=start_x.elf
fixup_file=fixup_x.dat
# When there are bad usb cables for 5V, don't care about it
# -no warning of low voltage
avoid_warnings=1
# -no CPU turbo stopping
avoid_warnings=2
# Provide maximum 5V current to USB devices, good for external harddisk
max_usb_current=1
# Allow sound after kernel update
# Enable audio (loads snd_bcm2835)
dtparam=audio=on
EOF
# Raspberry Pi wait for network - ddclient runs without errors
# https://www.raspberrypi.org/blog/latest-raspbian-update/
# https://github.com/RPi-Distro/raspi-config/commit/61bb3c381fa30d52151502bfdc9513065fa8ddd6
raspi-config nonint do_wait_for_network Slow
# Kernel - save data to disk after getting 6 seconds old with 8MB buffer
cat <<EOF > /etc/sysctl.d/30-rpi-optimizations.conf
vm.swappiness = 60
vm.min_free_kbytes = 8192
vm.vfs_cache_pressure = 500
vm.dirty_bytes = 8388608
vm.dirty_background_bytes = 8388608
vm.dirty_writeback_centisecs = 600
vm.dirty_expire_centisecs = 600
EOF
# Kernel - don't care about IPV6 at all, use only IPV4
cat <<EOF > /etc/sysctl.d/99-rpi-disable-ipv6.conf
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
EOF
# Xorg - don't black the screen at all
mkdir -p /etc/X11/xorg.conf.d/
cat <<EOF > /etc/X11/xorg.conf.d/50-on-flags.conf
Section "ServerFlags"
    Option "BlankTime" "0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "0"
EndSection
EOF
# Load all sysctl configuration files manually
sysctl --system
# Show the sysctl configurations to see if they look well
sysctl -a | grep disable | grep ipv6
# Set locale for US, not UK - it's hard to find special characters
sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
sed -i 's/# ro_RO.UTF-8 UTF-8/ro_RO.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen
localectl set-locale LANG=ro_RO.UTF8
localectl --no-convert set-keymap ro
localectl --no-convert set-x11-keymap ro pc105 ,dvorak grp:alt_shift_toggle
echo "KEYMAP=ro" > /etc/vconsole.conf
rm /etc/localtime
ln -sf /usr/share/zoneinfo/Europe/Bucharest /etc/localtime
sleep 1
# Get fresh repository status and upgrade installed packages
apt-get update && apt-get upgrade -y
# Install Firefox web browser - iceweasel installs firefox-esr
apt-get remove -y iceweasel
apt-get install -y firefox-esr
# Save all buffers to disk
sync
reboot
